# 1. LIBRERIAS Y FUNCIONES

In [1]:
import pandas as pd

# 2. PARÁMETROS

# 3. DATOS

In [2]:
df_bfv = pd.read_csv("data/black_friday_ventas.csv")
df_bfv.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

# 4. PROCESO

## 4.1 Revisión inicial de los datos

- Dimensiones del dataset

In [3]:
# número de filas y columnas
df_bfv.shape

(550068, 12)

In [4]:
# tipos de variables
df_bfv.dtypes

User_ID                         int64
Product_ID                        str
Gender                            str
Age                               str
Occupation                      int64
City_Category                     str
Stay_In_Current_City_Years        str
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

## 4.2. Calidad de los datos

In [5]:
# valores faltantes
df_bfv.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [14]:
# revisamos por producto
df_bfv[df_bfv['Product_Category_2'].isnull()].groupby(['Product_ID','Product_Category_1','Product_Category_2'],dropna=False).size().sort_values(ascending=False).head(10)

Product_ID  Product_Category_1  Product_Category_2
P00255842   16                  NaN                   1383
P00278642   5                   NaN                   1226
P00031042   8                   NaN                   1200
P00258742   5                   NaN                    964
P00110542   8                   NaN                    958
P00106042   5                   NaN                    905
P00371644   20                  NaN                    899
P00372445   20                  NaN                    837
P00156442   8                   NaN                    835
P00370853   19                  NaN                    818
dtype: int64

In [17]:
df_bfv[(df_bfv['Product_ID']=='P00255842')\
       #& (df_bfv['Product_Category_2'].notnull())
       ][['Product_ID','Product_Category_1','Product_Category_2','Purchase']]

       Product_ID  Product_Category_1  Product_Category_2  Purchase
234     P00255842                  16                 NaN     20961
506     P00255842                  16                 NaN     16416
1116    P00255842                  16                 NaN     12379
1460    P00255842                  16                 NaN     20742
1806    P00255842                  16                 NaN     16875
...           ...                 ...                 ...       ...
544846  P00255842                  16                 NaN     20283
544928  P00255842                  16                 NaN     20296
545007  P00255842                  16                 NaN     16874
545142  P00255842                  16                 NaN      8340
545461  P00255842                  16                 NaN     20634

[1383 rows x 4 columns]

# 5. SALIDA